language: objective-c
osx_image: xcode8.2

before_install:
  # bring in Cedar and other dependencies
  - git submodule update --init
  # try to start the iPhone simulator at least once
  - open -b com.apple.iphonesimulator

script: rake travis

